### ISSUE TITLE
Module not appearing

### ISSUE THREAD

**Issue by 3sclsn** [codetheweb/MMM-AnyList#14]
Hi, 
the AnyList module is not appearing on my screen. I cannot see any particular error. 
Is a basic (free) account enough for the module to work, or is perhaps a complete subscription necessary?
Thanks in advance,
Dries

**Comment by codetheweb** [comment]
It should work with free accounts.

Is there anything in the logs that might be helpful?

**Comment by 3sclsn** [comment]
Thanks. The module started working after a new update. 
It indeed works perfectly with a free AnyList account.
