### ISSUE TITLE
module not appearing

### ISSUE THREAD

**Issue by XoniBlue** [codetheweb/MMM-AnyList#15]
Hello, for the life of me I cannot get the module to show.  No errors in pm2 logs. ran npm -i everything went ok.

This is from console in chrome 
```
MMM-AnyList.js:59 Uncaught TypeError: Cannot read property 'name' of null
    at Class.socketNotificationReceived (MMM-AnyList.js:59)
    at module.js:250
    at Socket.<anonymous> (socketclient.js:39)
    at Socket../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
    at Socket.emitEvent (socket.js:253)
    at Socket.onevent (socket.js:240)
    at Socket.MMSocket.self.socket.onevent (socketclient.js:33)
    at Socket.onpacket (socket.js:204)
    at Manager.<anonymous> (index.js:21)
    at Manager../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
```
Below is my config, Ive tried ' and " around the parameters seems to not make a difference. 

```
		{
			module: 'MMM-AnyList',
			header: 'AnyList',
			position: 'top_right',
			config: {
			  email: "****",
			  password: "*******",
			  list: "target",
			  // Optional, values listed are the defaults
			  onlyShowUnchecked: false,
			  hideBullets: false,
			  maxItemsInList: 50,
			  highlightAlternateRows: 'true',
			  highlightColor: 'darkslategrey',
			  fade: false,
			  fadePoint: 0.5,
			  animationSpeed: 2000,
			}
		  },
```

**Comment by codetheweb** [comment]
I believe the null value originates [here](https://github.com/codetheweb/MMM-AnyList/blob/3af6643b4a2dfa50280ed356d8e3b2a82f95e4ab/node_helper.js#L27): `this.anylist.getListByName(list)`.

Are you sure the list is spelled right in the config? It's case-sensitive.

**Comment by XoniBlue** [comment]
yes i am sure the name is correct.

**Comment by codetheweb** [comment]
I'm sorry but there's not much more I can debug from my end.

I would try sprinkling a few `console.log()` statements in to check what `node_helper.js` is sending.

**Comment by XoniBlue** [comment]
rm -rf and tried from the beginning from ethernet instead of wifi and its working now. 
thank you for helping

**Comment by codetheweb** [comment]
Glad you got it working.
