### ISSUE TITLE
Issue getting module to appear

### ISSUE THREAD

**Issue by basedongauntlet** [codetheweb/MMM-AnyList#2]
Hello, I am having trouble getting my anylist list to appear on screen. The Magic Mirror program is not giving any errors as far as I can tell. 

I used the following command to get the files into the "modules" folder:

git clone https://github.com/codetheweb/MMM-AnyList.git

And added the following to config.js:

{
     module: "MMM-AnyList",
     position: "bottom_right",
     config: {
          email: "myemail",
          password: "mypassword",
          list: "Grocery List",
     }
},

Note:
I have MagicMirror2 2.12.0 (2020-07-01) 
I verified my email and password by logging in through web browser and on my phone. 
The list name as it appears in the app is "Grocery List" and it is a shared list with another user. 

Thank you in advance for any help. 

Sam

**Comment by codetheweb** [comment]
What does the server output look like? Does the module get loaded by the server and just not display on the frontend?

The output should be something like
```
[2020-07-15 19:08:32.284] [LOG]    Module helper loaded: MMM-AnyList
[2020-07-15 19:08:32.614] [LOG]    Initializing new module helper ...
...
[2020-07-15 19:08:32.614] [LOG]    All module helpers loaded.
[2020-07-15 19:08:32.691] [LOG]    Starting server on port 8080 ...
[2020-07-15 19:08:32.696] [LOG]    Server started ...
...
[2020-07-15 19:08:32.696] [LOG]    Connecting socket for: MMM-AnyList
[2020-07-15 19:08:32.696] [LOG]    Starting node helper: MMM-AnyList
```

**Comment by basedongauntlet** [comment]
The only output from the server that I can see is:

[2020-07-19 19:01:00.776] [LOG]     No helper found for module: MMM-AnyList.


Is there something else in the AnyList module directory that should be installed? 

Thank you,
Sam

**Comment by codetheweb** [comment]
Yes, that sounds like a server issue. Did you run `npm i` in `MMM-AnyList` after cloning?

**Comment by basedongauntlet** [comment]
I hadn't, but I just did. Module still does not appear and server output is the same that I stated previously.

**Comment by basedongauntlet** [comment]
Update: after running npm i I realized my syntax was incorrect in the config.js 

I changed "MMM-AnyList" to "MMM-Anylist" and now the server output is what you stated it should be. 

I still do not see the module though.

**Comment by codetheweb** [comment]
That's strange, `MMM-AnyList` should be correct.

What does `tree -L 2` give when inside your `modules/` folder?

**Comment by basedongauntlet** [comment]
Here is what it gives me:

pi@raspberrypi:~/MagicMirror/modules $ tree -L 2
.
├── default
│   ├── alert
│   ├── calendar
│   ├── clock
│   ├── compliments
│   ├── currentweather
│   ├── defaultmodules.js
│   ├── helloworld
│   ├── newsfeed
│   ├── updatenotification
│   ├── weather
│   └── weatherforecast
├── MMM-Anylist
│   ├── MMM-AnyList.css
│   ├── MMM-AnyList.js
│   ├── node_helper.js
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   └── README.md
├── mmm-hue-lights
│   ├── handlebars.runtime.min-v4.0.12.js
│   ├── icons
│   ├── LICENSE
│   ├── mmm-hue-lights.css
│   ├── mmm-hue-lights.js
│   ├── mmm-hue-lights-templates.js
│   ├── node_helper.js
│   ├── README.md
│   └── templates
└── MMM-RAIN-RADAR
    ├── images
    ├── LICENSE
    ├── MMM-RAIN-RADAR.css
    ├── MMM-RAIN-RADAR.js
    ├── node_helper.js
    └── README.md

18 directories, 19 files

**Comment by codetheweb** [comment]
Ok, I think the issue might be in how you cloned it. The folder `MMM-Anylist` should be called `MMM-AnyList` (hence why it sort of worked when you changed the name). I would suggest completely deleting the `MMM-Anylist` folder, running `git clone https://github.com/codetheweb/MMM-AnyList.git` to re-clone it, run `npm i` inside the module folder, and try again.

**Comment by basedongauntlet** [comment]
Got it! I re-cloned it as you suggested, and also updated the list name in the config file to "Grocery List" as it appears in the app instead of "Grocery_List". Thank you so much for the help!

**Comment by codetheweb** [comment]
Glad you got it working.
