### ISSUE TITLE
Sort order for Categories

### ISSUE THREAD

**Issue by mrbeare** [codetheweb/MMM-AnyList#21]
Hi, 

I love using MMM-AnyList but is there a way to leave the sort order as it is on the AnyList app (i.e. manual sort order and not alphabetical? This seems to be related to the latest update allowing categories.

Cheers
Paul

**Comment by codetheweb** [comment]
Sorry, this should be fixed in 481036b. Please pull from master to update.

**Comment by mrbeare** [comment]
Perfect thanks.
