### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by Gabian34** [codetheweb/MMM-AnyList#35]
Hello,

Since 2 days I got this message error INIT notification HTTP Error service unavailable code 503.No change from my side, everything was OK before. Other modules are OK. 
Any idea ?
Thanks for your answer...

**Comment by BenJamesFX** [comment]
Hey,
I am having the exact same problem aswell!
I thought it was at my end...spent last two days trying to sort with no joy.

Hopefully it gets fixed soon!

Many Thanks

**Comment by codetheweb** [comment]
Duplicate of https://github.com/codetheweb/anylist/issues/34
