### ISSUE TITLE
Multiple (3) lists not working

### ISSUE THREAD

**Issue by kevindeneault** [codetheweb/MMM-AnyList#8]
I have 3 lists in AnyList that I want to display and while 2 work, 3 do not. With 2, one is on top_left and the other is on top_right.
With 3, one is top_left while the other two are top_right but only one on the right displays.

**Comment by codetheweb** [comment]
> With 3, one is top_left while the other two are top_right but only one on the right displays.

I'm sorry, I'm not quite understanding what you're saying. This module's code doesn't have anything to do with the layout; MagicMirror controls layout of the different modules.

**Comment by kevindeneault** [comment]
Sorry about that. I copy pasted the MMM-AnyList section 3 times in config.js. The first one, top_left, displays. The second one, top_right, displays. For whatever reason the third one, under the second one, also set to top_left, does not display at all. No list title or anything. If I rearrange their order (the second and third lists), it changes which one displays. It's always the 3rd one in the file that does not show at all.

**Comment by codetheweb** [comment]
I see what you mean.

I believe it should be fixed now. Please update the module with `git pull` and try again.

**Comment by kevindeneault** [comment]
Excellent! It works great. Much appreciated. -Kevin

**Comment by codetheweb** [comment]
👍 that's great to hear!
